# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71af7953ffdaa122b63ae519b44bad204dd75aad4f64e2278b85e05b969182d454be83e7754cc2c226f4fd4be05a26e8f8b61e2d6c04916bb51da62b34c60ef2

test:
  secret_key_base: 3b660dd25821a5ad900bd1fe4fc17ad14a723580b4d1bce3bab44628d548701882d16b0f23cd30ed5192f8d50e5705bd90cdb3b2733144b6a181a10e3cad7211

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
